/*
 * This file is generated by jOOQ.
 */
package com.infiniteautomation.mango.temip.model;


import org.jooq.Field;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TemipRecord extends TableRecordImpl<TemipRecord> implements Record11<Integer, Integer, Integer, Integer, String, String, String, String, String, Integer, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>temip.id</code>.
     */
    public TemipRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>temip.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>temip.eventDetectorId</code>.
     */
    public TemipRecord setEventDetectorId(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>temip.eventDetectorId</code>.
     */
    public Integer getEventDetectorId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>temip.priority</code>.
     */
    public TemipRecord setPriority(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>temip.priority</code>.
     */
    public Integer getPriority() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>temip.alarmState</code>.
     */
    public TemipRecord setAlarmState(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>temip.alarmState</code>.
     */
    public Integer getAlarmState() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>temip.source</code>.
     */
    public TemipRecord setSource(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>temip.source</code>.
     */
    public String getSource() {
        return (String) get(4);
    }

    /**
     * Setter for <code>temip.category</code>.
     */
    public TemipRecord setCategory(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>temip.category</code>.
     */
    public String getCategory() {
        return (String) get(5);
    }

    /**
     * Setter for <code>temip.alarmText</code>.
     */
    public TemipRecord setAlarmText(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>temip.alarmText</code>.
     */
    public String getAlarmText() {
        return (String) get(6);
    }

    /**
     * Setter for <code>temip.timestamp</code>.
     */
    public TemipRecord setTimestamp(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>temip.timestamp</code>.
     */
    public String getTimestamp() {
        return (String) get(7);
    }

    /**
     * Setter for <code>temip.address</code>.
     */
    public TemipRecord setAddress(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>temip.address</code>.
     */
    public String getAddress() {
        return (String) get(8);
    }

    /**
     * Setter for <code>temip.port</code>.
     */
    public TemipRecord setPort(Integer value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>temip.port</code>.
     */
    public Integer getPort() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>temip.trapStatus</code>.
     */
    public TemipRecord setTrapStatus(String value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>temip.trapStatus</code>.
     */
    public String getTrapStatus() {
        return (String) get(10);
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row11<Integer, Integer, Integer, Integer, String, String, String, String, String, Integer, String> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    @Override
    public Row11<Integer, Integer, Integer, Integer, String, String, String, String, String, Integer, String> valuesRow() {
        return (Row11) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Temip.TEMIP.id;
    }

    @Override
    public Field<Integer> field2() {
        return Temip.TEMIP.eventDetectorId;
    }

    @Override
    public Field<Integer> field3() {
        return Temip.TEMIP.priority;
    }

    @Override
    public Field<Integer> field4() {
        return Temip.TEMIP.alarmState;
    }

    @Override
    public Field<String> field5() {
        return Temip.TEMIP.source;
    }

    @Override
    public Field<String> field6() {
        return Temip.TEMIP.category;
    }

    @Override
    public Field<String> field7() {
        return Temip.TEMIP.alarmText;
    }

    @Override
    public Field<String> field8() {
        return Temip.TEMIP.timestamp;
    }

    @Override
    public Field<String> field9() {
        return Temip.TEMIP.address;
    }

    @Override
    public Field<Integer> field10() {
        return Temip.TEMIP.port;
    }

    @Override
    public Field<String> field11() {
        return Temip.TEMIP.trapStatus;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getEventDetectorId();
    }

    @Override
    public Integer component3() {
        return getPriority();
    }

    @Override
    public Integer component4() {
        return getAlarmState();
    }

    @Override
    public String component5() {
        return getSource();
    }

    @Override
    public String component6() {
        return getCategory();
    }

    @Override
    public String component7() {
        return getAlarmText();
    }

    @Override
    public String component8() {
        return getTimestamp();
    }

    @Override
    public String component9() {
        return getAddress();
    }

    @Override
    public Integer component10() {
        return getPort();
    }

    @Override
    public String component11() {
        return getTrapStatus();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getEventDetectorId();
    }

    @Override
    public Integer value3() {
        return getPriority();
    }

    @Override
    public Integer value4() {
        return getAlarmState();
    }

    @Override
    public String value5() {
        return getSource();
    }

    @Override
    public String value6() {
        return getCategory();
    }

    @Override
    public String value7() {
        return getAlarmText();
    }

    @Override
    public String value8() {
        return getTimestamp();
    }

    @Override
    public String value9() {
        return getAddress();
    }

    @Override
    public Integer value10() {
        return getPort();
    }

    @Override
    public String value11() {
        return getTrapStatus();
    }

    @Override
    public TemipRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public TemipRecord value2(Integer value) {
        setEventDetectorId(value);
        return this;
    }

    @Override
    public TemipRecord value3(Integer value) {
        setPriority(value);
        return this;
    }

    @Override
    public TemipRecord value4(Integer value) {
        setAlarmState(value);
        return this;
    }

    @Override
    public TemipRecord value5(String value) {
        setSource(value);
        return this;
    }

    @Override
    public TemipRecord value6(String value) {
        setCategory(value);
        return this;
    }

    @Override
    public TemipRecord value7(String value) {
        setAlarmText(value);
        return this;
    }

    @Override
    public TemipRecord value8(String value) {
        setTimestamp(value);
        return this;
    }

    @Override
    public TemipRecord value9(String value) {
        setAddress(value);
        return this;
    }

    @Override
    public TemipRecord value10(Integer value) {
        setPort(value);
        return this;
    }

    @Override
    public TemipRecord value11(String value) {
        setTrapStatus(value);
        return this;
    }

    @Override
    public TemipRecord values(Integer value1, Integer value2, Integer value3, Integer value4, String value5, String value6, String value7, String value8, String value9, Integer value10, String value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TemipRecord
     */
    public TemipRecord() {
        super(Temip.TEMIP);
    }

    /**
     * Create a detached, initialised TemipRecord
     */
    public TemipRecord(Integer id, Integer eventdetectorid, Integer priority, Integer alarmstate, String source, String category, String alarmtext, String timestamp, String address, Integer port, String trapstatus) {
        super(Temip.TEMIP);

        setId(id);
        setEventDetectorId(eventdetectorid);
        setPriority(priority);
        setAlarmState(alarmstate);
        setSource(source);
        setCategory(category);
        setAlarmText(alarmtext);
        setTimestamp(timestamp);
        setAddress(address);
        setPort(port);
        setTrapStatus(trapstatus);
    }
}
